sudo: true
dist: trusty

language: cpp

cache:
  apt: true

addons:
  apt:
    packages:
    - libboost-dev
    - libboost-coroutine-dev
    - libboost-program-options-dev
    - libboost-serialization-dev
    - libboost-system-dev
    - libboost-all-dev

compiler:
  - g++

install:
  - sudo apt-get update -qq

script:
# Travis-CI linux distribution (14.04) 'trusty' does not at this time provide
# Boost 1.60 (or greater) which is required to be able to build Wye therefore
# do nothing for now. 
#  - autoreconf -fi
#  - ./configure
#  - (cd src; make)

