#!/usr/bin/env python

import wye
import tabulate
import sys

if len(sys.argv) != 2:
    sys.stderr.write("Usage:\n\tdelete-job <job>\n")
    sys.exit(1)

context = wye.StreamingContext()

context.delete_job(sys.argv[1])

