#!/usr/bin/env python

import sys
import wye

url = "http://localhost:8080"

context = wye.StreamingContext(url)

job = context.define_job(name="job1", description="A test job")

sink1 = job.define_python_worker("sink1", "sink.py")
sink2 = job.define_python_worker("sink2", "sink.py")

trans1 = job.define_python_worker("trans1", "t1.py", [sink1])
trans2 = job.define_python_worker("trans2", "t2.py", [sink2])

src = job.define_python_worker("source", "source.py", [trans1, trans2])

job_id = job.implement()

sys.stderr.write("Job %s is running.\n" % job_id)

