#!/usr/bin/env python

import sys
import wye


url = "http://localhost:8080"

context = wye.Context(url)

job = context.define_job(name="job1", description="An executable test job")

# Create 2 threads/instances running an executable
#exe = job.define_executable_worker("exe", "/usr/sbin/wireshark", parallelism=4)
exe = job.define_executable_worker("exe", "/usr/bin/watch -d ls -l", parallelism=2)

job_id = job.implement()

sys.stderr.write("Job %s is running.\n" % job_id)

