#!/usr/bin/env python

import sys
import wye


url = "http://localhost:8080"

context = wye.Context(url)

job = context.define_job(name="job1", description="An application test job")

# Create 2 threads/instances running an application
exe = job.define_application_worker("exe", "/usr/sbin/wireshark", parallelism=2)

job_id = job.implement()

sys.stderr.write("Job %s is running.\n" % job_id)

