#!/usr/bin/env python

import sys
import wye.context

url = "http://localhost:8080"

context = wye.context.StreamingContext(url)

job = context.define_job(name="job1", description="A test job")

sink = job.define_python_worker("sink", "sink.py", parallelism=1)

trans = job.define_lambda_worker("trans", lambda x: [x, x * x],
                                 {	  	 
                                     "output": [(sink,"input")]
                                 })

src = job.define_python_worker("source", "source_nums.py",
                               {
                                   "output": [(trans,"input")]
                               })

job_id = job.implement()

sys.stderr.write("Job %s is running.\n" % job_id)

