#!/usr/bin/env python

import wye
import tabulate

try:
    url = sys.argv[1]
except:
    url = "http://localhost:8080/"

context = wye.Context(url)

jobs = context.get_jobs()

table = []

for j in jobs:
    table.append([j,
                  jobs[j].get("name",""),
                  jobs[j].get("description","")])

header = ["id", "name", "description"]
print tabulate.tabulate(table, headers=header)

