#!/usr/bin/env python

import wye
import tabulate
import sys

try:
    id = sys.argv[1]
except:
    sys.stderr.write("Usage:\n\twye-delete-worker <id> [<url>]\n")
    sys.exit(1)

try:
    url = sys.argv[2]
except:
    url = "http://localhost:8080/"

context = wye.Context(url)

context.delete_worker(id)

