#!/usr/bin/env python

import wye.context
import tabulate
import sys

if len(sys.argv) != 2:
    sys.stderr.write("Usage:\n\tget-job <job>\n")
    sys.exit(1)

context = wye.context.StreamingContext()

job = context.get_job(sys.argv[1])

print

print "%-20s: %s" % ("id", sys.argv[1])
if job.has_key("name"):
    print "%-20s: %s" % ("name", job["name"])
if job.has_key("description"):
    print "%-20s: %s" % ("description", job["description"])
print

table = []

workers = job["workers"]

for w in workers:
    table.append([w,
                  workers[w].get("name",""),
                  workers[w].get("job_id",""),
                  workers[w].get("state","")])

header = ["worker id", "name", "job", "state"]
print tabulate.tabulate(table, headers=header)




