#!/usr/bin/env python

import wye
import tabulate
import sys

try:
    id = sys.argv[1]
except:
    sys.stderr.write("Usage:\n\twye-delete-worker <id> [<url>]\n")
    sys.exit(1)

try:
    url = sys.argv[2]
except:
    url = "http://localhost:8080/"

context = wye.Context(url)

worker = context.get_worker(id)

print "%-20s %s" % ("id:", sys.argv[1])
if worker.has_key("name"):
    print "%-20s %s" % ("name:", worker["name"])
if worker.has_key("state"):
    print "%-20s %s" % ("state:", worker["state"])
if worker.has_key("exec"):
    print "%-20s %s" % ("exec:", worker["exec"])
if worker.has_key("args"):
    t = "args:"
    for a in worker["args"]:
        print "%-20s %s" % (t, a)
        t = ""
if worker.has_key("inputs"):
    t = "inputs:"
    for a in worker["inputs"]:
        print "%-20s %s:" % (t, a)
        print "%-20s   %s" % ("", worker["inputs"][a])
        t = ""
        
if worker.has_key("outputs"):
    t = "outputs:"
    for a in worker["outputs"]:
        for x in worker["outputs"][a]:
            print "%-20s %s:" % (t, a)
            outs = ""
            for y in x:
                print "%-20s   %s" % ("", y)
            t = ""
