#!/usr/bin/env python

import wye
import tabulate
import sys

try:
    id = sys.argv[1]
except:
    sys.stderr.write("Usage:\n\twye-get-job <id> [<url>]\n")
    sys.exit(1)

try:
    url = sys.argv[2]
except:
    url = "http://localhost:8080/"

context = wye.Context(url)

job = context.get_job(id)

print

print "%-20s: %s" % ("id", sys.argv[1])
if job.has_key("name"):
    print "%-20s: %s" % ("name", job["name"])
if job.has_key("description"):
    print "%-20s: %s" % ("description", job["description"])
print

table = []

workers = job["workers"]

for w in workers:
    table.append([w,
                  workers[w].get("name",""),
                  workers[w].get("job_id",""),
                  workers[w].get("state","")])

header = ["worker id", "name", "job", "state"]
print tabulate.tabulate(table, headers=header)




