#!/usr/bin/env python

import wye
import tabulate

try:
    url = sys.argv[1]
except:
    url = "http://localhost:8080/"

context = wye.Context(url)

workers = context.get_workers()

table = []

for w in workers:
    table.append([w,
                  workers[w].get("name",""),
                  workers[w].get("job_id",""),
                  workers[w].get("state","")])

header = ["id", "name", "job", "state"]
print tabulate.tabulate(table, headers=header)



