#!/usr/bin/env python

import wye
import sys

try:
    url = sys.argv[1]
except:
    url = "http://localhost:8080/"

context = wye.Context(url)

workers = context.get_workers()

for w in workers:
    state = workers[w].get("state","")

    if state != "RUNNING":

        sys.stderr.write("Worker %s (%s) is not RUNNING.\n" %
                         (workers[w].get("name", ""),
                          workers[w].get("job_id", "")))

        sys.exit(1)

sys.stderr.write("All workers are running.\n")

sys.exit(0)


